### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by dardam** [Lance5057/Tinkers-Compendium#75] opened 2018-10-11 01:17 UTC
Crash on server when wearing armor

**Comment by Lance5057** [comment] 2018-10-11 01:19
`net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
	at lance5057.tDefense.core.materials.traits.TraitPhotosynthetic.onArmorTick(TraitPhotosynthetic.java:28) ~[TraitPhotosynthetic.class:?]
	at lance5057.tDefense.core.tools.TDToolEvents.onArmorTick(TDToolEvents.java:124) ~[TDToolEvents.class:?]
	at lance5057.tDefense.core.tools.TDToolEvents.ArmorTick(TDToolEvents.java:79) ~[TDToolEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_724_TDToolEvents_ArmorTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more`

**Comment by Lance5057** [comment] 2018-10-11 01:19
```
java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V at lance5057.tDefense.core.materials.traits.TraitPhotosynthetic.onArmorTick(TraitPhotosynthetic.java:28)
```

**Comment by Lance5057** [comment] 2019-01-30 07:09
This should be fixed in the latest update.

**Closed by Lance5057** 2019-01-30 07:09 UTC
Labels: Fixed, bug
